@baseUrl = http://127.0.0.1:8000/api/v1
@token = eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjEzMzkwMzkwLCJqdGkiOiI4ODM2ZDFiYmQxZjc0YzkxOGNjZDZhMDliZTQxNDhlZSIsInVzZXJfaWQiOjF9.LOi3sUy2MbS6-CLtrJFzSiismiGGpEFzX7Ci0pgL0JU
###

POST {{baseUrl}}/auth/email/
Content-Type: application/json

{
    "email": "testtoken@myemail.com"
}

###

POST {{baseUrl}}/auth/token/
Content-Type: application/json

{
    "email": "testtoken@myemail.com",
    "confirmation_code": "5o5-601fcc1af6976a8a460e"
}


###

GET {{baseUrl}}/users/me/
Content-Type: application/json
Authorization: Bearer {{token}}

###

PATCH {{baseUrl}}/users/me/
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "role": "admin"
}

###

GET {{baseUrl}}/users/
Content-Type: application/json
Authorization: Bearer {{token}}

###

GET {{baseUrl}}/users/test/
Content-Type: application/json
Authorization: Bearer {{token}}

###

PATCH {{baseUrl}}/users/testtest/
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "first_name": "test name"
}

###

GET {{baseUrl}}/titles/1/reviews
Content-Type: application/json
Authorization: Bearer {{token}}

###

POST {{baseUrl}}/titles/1/reviews/
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "text": "Try to make second review",
    "score": 5
}

###

GET {{baseUrl}}/titles/1
Content-Type: application/json
Authorization: Bearer {{token}}

###

GET {{baseUrl}}/titles/?genre=t1
Content-Type: application/json
Authorization: Bearer {{token}}

###

GET {{baseUrl}}/titles/
Content-Type: application/json
Authorization: Bearer {{token}}
