@baseUrl = http://127.0.0.1:8000/api/v1
@token = eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjEzMjYyODc2LCJqdGkiOiJkNzVkOTY4NzIxMTU0YjBiOGY1YWZiMDVjNjJjYjNhNSIsInVzZXJfaWQiOjV9.Am55Dkb3Xq1AvDnabA--VvH8tOMGlfXX83bksu1fwBA
###

POST {{baseUrl}}/auth/email/
Content-Type: application/json

{
    "email": "tesrrrtt@myemail.com"
}

###

POST {{baseUrl}}/auth/token/
Content-Type: application/json

{
    "email": "tesrrrtt@myemail.com",
    "confirmation_code": "5o4-349835f2f5c0eee27f01"
}


###

GET {{baseUrl}}/users/me/
Content-Type: application/json
Authorization: Bearer {{token}}

###

PATCH {{baseUrl}}/users/me/
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "role": "admin"
}

###

GET {{baseUrl}}/users/
Content-Type: application/json
Authorization: Bearer {{token}}

###

GET {{baseUrl}}/users/testtest/
Content-Type: application/json
Authorization: Bearer {{token}}

###

PATCH {{baseUrl}}/users/testtest/
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "first_name": "test name"
}

###

GET {{baseUrl}}/titles/?genre=t1
Content-Type: application/json
Authorization: Bearer {{token}}

###

GET {{baseUrl}}/titles/
Content-Type: application/json
Authorization: Bearer {{token}}
